# Generated by Django 3.1.7 on 2022-01-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('currency', models.CharField(default='₹', max_length=3)),
                ('image', models.ImageField(upload_to='products/')),
                ('stock', models.BooleanField(default=True)),
            ],
        ),
    ]
